# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: ingsitemap
#   labels:
#     app: ingsitemap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingsitemap
  namespace: kube-system
  labels:
    app: ingsitemap
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ingsitemap
  labels:
    app: ingsitemap
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ingsitemap
  labels:
    app: ingsitemap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingsitemap
subjects:
  - kind: ServiceAccount
    name: ingsitemap
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingsitemap
  namespace: kube-system
  labels:
    app: ingsitemap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingsitemap
      release: ingsitemap
  template:
    metadata:
      labels:
        app: ingsitemap
        release: ingsitemap
    spec:
      serviceAccountName: ingsitemap
      containers:
      - name: ingsitemap
        image: "registry.cn-shenzhen.aliyuncs.com/infrastlabs/ingsitemap:latest"
        imagePullPolicy: Always
        # command:
        # - cp
        # args:
        # - -jumpurl=http://ingsitemap-svc
        env:
          - name: AUTO_INGRESS_SERVER_NAME
            value: "demo1.cn"
          - name: GW_HTTP_PORT
            value: "32603"
          - name: GW_HTTPS_PORT
            value: "31714"
            

        # these liveness probes use the metrics endpoint
        # readinessProbe:
        #   httpGet:
        #     scheme: HTTP
        #     path: /metrics
        #     port: 8080
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 3
        #   periodSeconds: 3
        #   failureThreshold: 3
        # livenessProbe:
        #   httpGet:
        #     scheme: HTTP
        #     path: /metrics
        #     port: 8080
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 3
        #   periodSeconds: 10
        #   failureThreshold: 3
        securityContext:
          runAsUser: 1200
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        # ports:
        #   # metrics port
        #   - name: http-metrics
        #     containerPort: 8080
        #     protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ingsitemap-svc
  namespace: kube-system
  labels:
    app: ingsitemap-svc
spec:
  ports:
    - port: 9010
      name: http
      targetPort: 9010
  selector:
    app: "ingsitemap"
  type: NodePort
